# Settings in the [build] context are global and are applied to 
# all contexts unless otherwise overridden by more specific contexts.
[build]

  # Default build command.
  command = "echo Building"
  ignore = "node ignore_build.js"
